name: control_builder
description: Builder for control_core code generation.
version: 0.5.0-beta

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  control_annotations:
    path: ../control_annotations

  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  build_test: ^2.2.0
  test: ^1.25.2
