name: control_builder
description: Builder for control_core code generation.
version: 0.5.0-beta

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  control_annotations:
    path: ../control_annotations

  analyzer: ^9.0.0
  build: ^4.0.3
  source_gen: ^4.1.1
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.10.4
