name: localino_live
description: Implementation of LocalinoRemoteApi via Localino REST API.
homepage: https://localino.app
repository: https://github.com/romanbase/flutter_control
version: 1.3.0-beta.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/control_core
  control_core: ">=2.0.0-beta.2 <3.0.0"

  # https://pub.dev/packages/localino
  localino: ">=1.3.0-beta.1 <2.0.0"

  # https://pub.dev/packages/http
  http: ">=1.0.0 <2.0.0"

  # https://pub.dev/packages/path_provider
  path_provider: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


