name: parser_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_control:
    path: ../../

  control_annotations:
    path: ../../modules/control_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter

  process_run: ^1.2.4
  build_runner: ^2.10.4

  control_builder:
    path: ../../modules/control_builder

flutter:
  uses-material-design: true
