name: spends
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_control:
    path: ../../

  #https://github.com/FirebaseExtended/flutterfire
  firebase_core:
  firebase_auth:
  cloud_firestore:
  cloud_functions:
  firebase_analytics:

  google_sign_in:


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/localization/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
