name: control_config
description: Wrapper around shared_preferences
repository: https://github.com/romanbase/flutter_control
version: 1.4.0-beta.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/control_core
  control_core: ">=2.0.0-beta.1 <3.0.0"

  # https://pub.dartlang.org/packages/shared_preferences
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  lints: ^3.0.0
  flutter_lints: ^3.0.0

