name: counter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: 0.20.2

  flutter_control:
    path: ../../

  localino_live:
    path: ../../modules/localino_live

dev_dependencies:
  flutter_test:
    sdk: flutter

  # dart run build_runner build
  build_runner: 2.4.6

  localino_builder:
    path: ../../modules/localino_builder

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/localization/


